"""Static icon legacy name map and cursor alias map."""

ICON_LEGACY_NAMES = {
    # actions
    'application-exit':         ['gtk-quit', 'exit', 'xfce-system-exit'],
    'document-new':             ['gtk-new', 'stock_new-text', 'filenew'],
    'document-open':            ['gtk-open', 'fileopen'],
    'document-save':            ['gtk-save', 'stock_save', 'filesave'],
    'document-save-as':         ['gtk-save-as', 'stock_save-as', 'filesaveas'],
    'document-print':           ['gtk-print', 'stock_print', 'fileprint'],
    'document-revert':          ['gtk-revert-to-saved-ltr', 'revert'],
    'edit-clear':               ['gtk-clear', 'editclear'],
    'edit-copy':                ['gtk-copy', 'stock_copy', 'editcopy'],
    'edit-cut':                 ['gtk-cut', 'stock_cut', 'editcut'],
    'edit-delete':              ['gtk-delete', 'stock_delete', 'editdelete'],
    'edit-find':                ['gtk-find', 'stock_search', 'filefind', 'find'],
    'edit-find-replace':        ['gtk-find-and-replace', 'stock_search-and-replace'],
    'edit-paste':               ['gtk-paste', 'stock_paste', 'editpaste'],
    'edit-redo':                ['gtk-redo-ltr', 'stock_redo', 'redo'],
    'edit-select-all':          ['gtk-select-all', 'stock_select-all'],
    'edit-undo':                ['gtk-undo-ltr', 'stock_undo', 'undo'],
    'format-text-bold':         ['gtk-bold', 'stock_text_bold', 'text_bold'],
    'format-text-italic':       ['gtk-italic', 'stock_text_italic', 'text_italic'],
    'format-text-underline':    ['gtk-underline', 'stock_text_underlined', 'text_under'],
    'go-bottom':                ['gtk-goto-bottom', 'stock_bottom', 'bottom'],
    'go-down':                  ['gtk-go-down', 'stock_down', 'down'],
    'go-first':                 ['gtk-goto-first-ltr', 'stock_first', 'start'],
    'go-home':                  ['gtk-home', 'stock_home', 'gohome', 'kfm_home'],
    'go-last':                  ['gtk-goto-last-ltr', 'stock_last', 'finish'],
    'go-next':                  ['gtk-go-forward-ltr', 'stock_right', 'forward', 'next'],
    'go-previous':              ['gtk-go-back-ltr', 'stock_left', 'back', 'previous'],
    'go-top':                   ['gtk-goto-top', 'stock_top', 'top'],
    'go-up':                    ['gtk-go-up', 'stock_up', 'up'],
    'help-about':               ['gtk-about', 'stock_about', 'gnome-help', 'help-browser'],
    'help-contents':            ['gtk-help', 'stock_help', 'help'],
    'list-add':                 ['gtk-add', 'add'],
    'list-remove':              ['gtk-remove', 'remove'],
    'media-playback-pause':     ['gtk-media-pause', 'stock_media-pause', 'player_pause'],
    'media-playback-start':     ['gtk-media-play-ltr', 'stock_media-play', 'player_play'],
    'media-playback-stop':      ['gtk-media-stop', 'stock_media-stop', 'player_stop'],
    'media-record':             ['gtk-media-record', 'stock_media-rec', 'player_record'],
    'media-seek-backward':      ['gtk-media-rewind-ltr', 'stock_media-rew', 'player_rew'],
    'media-seek-forward':       ['gtk-media-forward-ltr', 'stock_media-fwd', 'player_fwd'],
    'process-stop':             ['gtk-stop', 'stock_stop', 'stop'],
    'system-lock-screen':       ['gnome-lockscreen', 'lock'],
    'system-log-out':           ['gnome-logout', 'gnome-session-logout', 'exit'],
    'system-run':               ['gnome-run', 'gtk-execute'],
    'system-search':            ['gnome-searchtool', 'search', 'kfind'],
    'view-fullscreen':          ['gtk-fullscreen', 'stock_fullscreen'],
    'view-refresh':             ['gtk-refresh', 'stock_refresh', 'reload', 'reload3'],
    'window-close':             ['gtk-close', 'stock_close'],
    'zoom-fit-best':            ['zoom-best-fit', 'gtk-zoom-fit', 'viewmagfit'],
    'zoom-in':                  ['gtk-zoom-in', 'stock_zoom-in', 'viewmag+'],
    'zoom-original':            ['gtk-zoom-100', 'stock_zoom-1', 'viewmag1'],
    'zoom-out':                 ['gtk-zoom-out', 'stock_zoom-out', 'viewmag-'],
    # apps
    'preferences-desktop-theme':['gnome-settings-theme', 'style'],
    'preferences-system':       ['gtk-preferences', 'package_settings', 'gnome-settings'],
    'system-file-manager':      ['file-manager', 'kfm'],
    'utilities-terminal':       ['gnome-terminal', 'konsole', 'terminal'],
    # places
    'folder':                   ['gnome-fs-directory', 'gtk-directory', 'stock_folder',
                                 'inode-directory'],
    'folder-open':              ['stock_open', 'folder_open'],
    'user-desktop':             ['gnome-fs-desktop', 'desktop'],
    'user-home':                ['gnome-fs-home', 'folder_home'],
    'user-trash':               ['gnome-fs-trash-empty', 'emptytrash', 'trashcan_empty',
                                 'gnome-stock-trash', 'xfce-trash_empty'],
    # mimetypes
    'application-x-executable': ['gnome-fs-executable',
                                  'gnome-mime-application-x-executable', 'binary', 'exec'],
    'audio-x-generic':          ['gnome-mime-audio', 'sound'],
    'image-x-generic':          ['gnome-mime-image', 'image'],
    'text-x-generic':           ['gnome-mime-text', 'ascii', 'empty', 'txt', 'unknown'],
    'video-x-generic':          ['gnome-mime-video', 'video'],
    # status
    'dialog-error':             ['gtk-dialog-error', 'stock_dialog-error', 'error'],
    'dialog-information':       ['gtk-dialog-info', 'stock_dialog-info', 'info'],
    'dialog-question':          ['gtk-dialog-question', 'stock_dialog-question'],
    'dialog-warning':           ['gtk-dialog-warning', 'stock_dialog-warning', 'important'],
    'folder-drag-accept':       ['gnome-fs-directory-accept'],
    'user-trash-full':          ['gnome-fs-trash-full', 'trashcan_full', 'edittrash'],
}

